version: '3'

networks:
  tessera:

volumes:
  mariadb:

services:

  mariadb:
    image: mariadb:10.6
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    networks:
      - tessera
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=tessera
      - MARIADB_USER=tessera
      - MARIADB_PASSWORD=tessera

  phpmyadmin:
    image: phpmyadmin:5.1
    restart: always
    depends_on:
      - mariadb
    ports:
      - 127.0.0.1:3307:80
    networks:
      - tessera
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
